config/routes.rb
Rails.application.routes.draw do
  get 'jss/index'

  get 'csss/index'

  get 'htmls/index'

  get 'rubys/index'

  get 'home/index'

  root 'home#index'

  resources :snippets

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :snippets, dependent: :nullify

  validates :title, presence: true, uniqueness: true
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :Category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/csss_controller.rb
class CsssController < ApplicationController
  def index
    @snippets = Snippet.where(category_id:3).order(created_at: :desc)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    @snippets = Snippet.order(created_at: :desc)
  end

end

app/controllers/htmls_controller.rb
class HtmlsController < ApplicationController
  def index
    @snippets = Snippet.where(category_id:2).order(created_at: :desc)
  end
end

app/controllers/jss_controller.rb
class JssController < ApplicationController
  def index
    @snippets = Snippet.where(category_id:4).order(created_at: :desc)
  end
end

app/controllers/rubys_controller.rb
class RubysController < ApplicationController
  def index
    @snippets = Snippet.where(category_id:1).order(created_at: :desc)
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  def index
    @snippets = Snippet.all
  end

  def new
    @snippet = Snippet.new
  end

  def create
    category = Category.find snippet_params[:category_id]
    snippet_params[:body] = "~~~~~#{category.name.downcase}\n#{snippet_params[:body]}\n~~~~~"
    @snippet = Snippet.new(snippet_params)
    @snippet.save
    redirect_to @snippet
  end

  def show
    @snippet = Snippet.find params[:id]
  end


  private
    def snippet_params
      params.require(:snippet).permit(:title, :body, :category_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  class CodeRayify < Redcarpet::Render::HTML
   def block_code(code, language)
     CodeRay.scan(code, language).div
   end
  end

  def markdown(text)
   coderayified = CodeRayify.new(:filter_html => true,
                                 :hard_wrap => true)
   options = {
     :fenced_code_blocks => true,
     :no_intra_emphasis => true,
     :autolink => true,
     :lax_html_blocks => true,
   }
   markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
   markdown_to_html.render(text).html_safe
  end
end

app/helpers/csss_helper.rb
module CsssHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/htmls_helper.rb
module HtmlsHelper
end

app/helpers/jss_helper.rb
module JssHelper
end

app/helpers/rubys_helper.rb
module RubysHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/csss/index.html.erb
<h1>Css</h1>
<% @snippets.each do |snips| %>
  <%= snips.title %>
  <%=  markdown(snips.body) %>
<% end %>

app/views/home/index.html.erb
<h1>Code Snippets</h1>

<%= link_to "Ruby(#{@snippets.where(category_id:1).length})", rubys_index_path %>
<br />
<%= link_to "HTML(#{@snippets.where(category_id:2).length})", htmls_index_path %>
<br />
<%= link_to "CSS(#{@snippets.where(category_id:3).length})", csss_index_path %>
<br />
<%= link_to "Javascript(#{@snippets.where(category_id:4).length})", jss_index_path %>

app/views/htmls/index.html.erb
<h1>Htmls</h1>
<% @snippets.each do |snips| %>
  <%= snips.title %>
  <%=  markdown(snips.body) %>
<% end %>

app/views/jss/index.html.erb
<h1>Javascript</h1>
<% @snippets.each do |snips| %>
  <%= snips.title %>
  <%=  markdown(snips.body) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snippeter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "Code Snippeter", new_snippet_path %>
  <%= link_to "Home", root_path %>
<%= yield %>

</body>
</html>

app/views/rubys/index.html.erb
<h1>Ruby</h1>
<% @snippets.each do |snips| %>
  <%= snips.title %>
  <%=  markdown(snips.body) %>
<% end %>

app/views/snippets/index.html.erb
<h1> All Snippets </h1>
<% @snippets.each do |snips| %>
  <%= snips.title %>
  <%=  markdown(snips.body) %>
<% end %>

app/views/snippets/new.html.erb
<h1>Code Snippets</h1>
<%= form_for @snippet do |f| %>
  <p>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/snippets/show.html.erb
<h1>Show Snippets</h1>
<%= @snippet.title %>
<%=  markdown(@snippet.body) %>